---
kind: pipeline
type: docker
name: default

steps:
- name: Test
  image: python:3.9
  commands:
  - pip install -r requirements.txt
  - pytest
- name: Format
  image: python:3.9
  commands:
  - make fmt
- name: Lint 
  image: python:3.9
  commands:
  - make lint

trigger:
  ref:
  - "refs/tags/*"
...
